locals {
  # ── MinIO internal credentials ────────────────────────────────────────────────
  # Access key (username) is not sensitive — kept as a fixed known value.
  minio_access_key = "loki"

  # Secret key is generated by random_password.minio_secret in main.tf.
  # Falls back to "" when MinIO is disabled (is_minio_enabled = false) so that
  # this local is always defined regardless of the count on the resource.
  minio_secret_key = local.is_minio_enabled ? random_password.minio_secret[0].result : ""

  minio_bucket   = "loki-chunks"
  minio_endpoint = "${var.instance_name}-minio.${local.namespace}.svc.cluster.local:9000"

  # ── Constructed default MinIO values ─────────────────────────────────────────
  constructed_minio_values = {
    fullnameOverride = "${var.instance_name}-minio"

    rootUser     = local.minio_access_key
    rootPassword = local.minio_secret_key

    mode = "standalone"

    buckets = [
      {
        name   = local.minio_bucket
        policy = "none"
        purge  = false
      }
    ]

    persistence = {
      enabled      = true
      size         = "10Gi"
      storageClass = null
    }

    resources = {
      requests = {
        cpu    = "100m"
        memory = "128Mi"
      }
      limits = {
        cpu    = "500m"
        memory = "512Mi"
      }
    }

    nodeSelector = local.node_selector
    tolerations  = local.tolerations

    metrics = {
      serviceMonitor = {
        enabled = local.prometheus_enabled
      }
    }
  }
}
